name: Feature Request
description: Suggest an improvement or enhancement for an existing skill
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: input
    id: skill-name
    attributes:
      label: Skill Name
      description: Which skill would this feature enhance? (Leave blank if suggesting a new skill)
      placeholder: e.g., api-builder, data-analyzer

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - Enhancement to existing skill
        - New capability for existing skill
        - Documentation improvement
        - Supporting scripts/tools
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What limitation does it address?
      placeholder: Describe the problem or limitation...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought about...

  - type: textarea
    id: examples
    attributes:
      label: Use Cases and Examples
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example 1: ...
        Example 2: ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve workflow
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Links to similar features
        - Screenshots or mockups
        - Related issues

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I can help test this feature once implemented
        - label: I can provide additional feedback and clarification

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the repository's purpose
          required: true
        - label: I have provided clear use cases for this feature
          required: true
